### ISSUE TITLE
Learn how to make an R package

### ISSUE THREAD

**Issue by njtierney** [numbats/numbathack18#16]
I am happy to run through how to create an R package - in this you will learn:

* How to create a skeleton of an R package
* Add some documentation and examples
* Put it up on github
* add a packagedown website (like naniar.njtierney.com)

**Comment by NTomasetti** [comment]
I"d be interested to learn

**Comment by njtierney** [comment]
Let's work on this after lunch

**Comment by njtierney** [comment]
Thanks everyone! We did it!
